### ISSUE TITLE
Optionen zur intuitiveren Installation und Offline-Nutzung

### ISSUE THREAD

**Issue by valioDOTch** [PiratenparteiBW/ua-ausweis-transliteration-web#3]
Soweit ich es verstehe funktioniert die App völlig offline als ZIP-Datei.

Ich finde das grundsätzlich eine sehr praktikable Lösung aber möchte anregen andere Optionen zu erwägen, um eine grössere Nutzergruppe zu erreichen.

Hierzu gibt es 2 verbreitete Ansätze:
* Nutzung des Progressive-Web-App-Ansatzes
* Verwendung von Electron zur Kompilierung und Publikation als App

Der zweite Ansatz wäre zwar interessant (da AppStores für User der bekannte Anlaufpunkt sind), aber ist umständlich und vom Nutzen-Ertrag-Verhältnis völlig ungeeignet für ein Projekt dieser Grösse.

Der erste Ansatz hingegen ist recht einfach; die Installation läuft über den Browser.
Ich kann hier auch beraten, da ich selbst in den Anfangstagen des Standards eine recht komplexe App umsetzen musste (mit lokaler DB und asynchronem Syncing für alle Browser).

**Comment by valioDOTch** [comment]
In erster Linie bräuchte es
* ein App-Icon für Smartphones v.a.; bevorzugt als Vorlage im SVG-Format via Inkscape, ggf. mit Teilen aus openclipart.org o.ä.
* ein WebAppManifest.JSON https://developer.mozilla.org/de/docs/Web/Manifest
* einen seeehr einfachen ServiceWorker.JS  https://developer.mozilla.org/de/docs/Web/API/Service_Worker_API
* kleine Ergänzungen an der index.html-Datei

Für einige Arbeitsschritte gibt es auch fertige Tools um Templates zu generieren
Auf Anhieb gefunden aber noch nicht im Detail studiert etwa
* https://www.dev-insider.de/praktische-helfer-fuer-progressive-web-apps-a-995204/
* https://tomitm.github.io/appmanifest/

**Comment by derBorys** [comment]
Vielen Dank für das Feedback.
Da wir aktuell nicht wissen in welche Richtung sich das Projekt entwickelt warten wir mit weiteren Umsetzungen ab.

Unsere Lösung richtet sich vornehmlich an Gemeinden die aktuell das Problem haben ukrainische Namen nicht rechts konform übersetzen zu können, was dazu führt das die Abarbeitung der einzelnen Fälle stockt. Sobald das BMI die entsprechende Translationstabelle veröffentlicht können mit unserer Lösung die Gemeinden loslegen.

Hierfür ist unser Ansatz aktuell der praktischste.

Wir werden sehen was die Woche jetzt bringt.

**Comment by valioDOTch** [comment]
Point taken.
War gestern nicht mehr ganz wach und zu wenig am Projektziel.
Mea culpa.
