### ISSUE TITLE
lateinische Ausgabe ist teilweise kyrillisch

### ISSUE THREAD

**Issue by ukcb** [PiratenparteiBW/ua-ausweis-transliteration-web#4]
siehe Screenshot

![Transliteration](https://user-images.githubusercontent.com/22983914/161312696-cd882e1b-3310-4e82-aa9c-1524e04f665f.png)

Update: Sorry, ich sehe gerade, dass das ы im ukrainischen-kyrillisch gar nicht auf der Tastatur ist. Wäre nett, wenn man die Sprache/Tastatur noch auf russisch-kyrillisch umstellen könnte.

**Comment by promasu** [comment]
Die Transliteration ist rein für ukrainische Dokumente und damit ukrainisch-kyrillische Schrift.
